# Generated by Django 5.2.5 on 2025-09-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
